#ifndef MODULARCORE_GLOBAL_H
#define MODULARCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULARCORE_LIBRARY)
#  define MODULARCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULARCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULARCORE_GLOBAL_H
