#ifndef MODULEDEFINES_H
#define MODULEDEFINES_H

#define __MODULE_GENERIC_VERIFICATION_STRING "9_Generic_Library_^^\x88\x23\xBB"
#define __MODULE_GENERIC_LIB_NAME "GenericLibrary"

#endif // MODULEDEFINES_H
